### PR TITLE
h/w to MAY to not prejudice against pure audio

### LINKED ISSUE #1361: Consistency of normative statements for image and non-image resources
The _SHOULDs_ and _MAYs_ on `height`, `width` and `duration` for Canvas (http://prezi3.iiif.io/api/presentation/3.0/#height) favour spatial coordinates over temporal (_SHOULD_ have a `width` but _MAY_ have a `duration`).

The normative language here could get very complex... _MUST_ have a height if it doesn't have a duration; _MAY_ have a duration if it has width and height; _MUST_ have duration if no width/height... and so on.

Also. as a sometime front end developer I suggest that dimensions of all content resources are _SHOULDs_ rather than _MAYs_, subject to the same combination clarifications.

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #1361  (despite what the branch name implies)

### CODE REVIEW

**Comment by zimeon** [comment]
I don't think I agree with the change from *render* to *explicitly display* for a couple of reasons:

  1. what does *explicitly* add to *display*? (Displaying something seems pretty explicit)
  2. why is *display* better than *render*? (To my ear, "render an audio track" makes more sense that "display an audio track")

Am I missing something?

**Comment by azaroth42** [comment]
@zimeon I can back that out, but the thought was that you need to process the dimension (e.g. create a canvas of the correct width) but you don't need to explicitly render the value of the dimension to the user. Just remove the render/display bits completely?

**Comment by tomcrane** [comment]
If we do keep the render/display bit, I think the text should be 

> ... _MAY_ display the value of ...

However, I don't think the spec needs to mention this at all; if a client feels the need to do this (perhaps it's a content creation tool, not a viewer) then it will just do it.

**Comment by azaroth42** [comment]
Fixed. Reviewable again now

**Pull request merged**
