### PR TITLE
Initial 0.4 changes

### PR DESCRIPTION
**Pull request by azaroth42**
Closes:
  * https://github.com/IIIF/discovery/issues/56
  * https://github.com/IIIF/discovery/issues/55
  * https://github.com/IIIF/discovery/issues/53
  * https://github.com/IIIF/discovery/issues/52
  * https://github.com/IIIF/discovery/issues/49
  * https://github.com/IIIF/discovery/issues/58

### CODE REVIEW

**Comment by azaroth42** [comment]
Preview:  https://preview.iiif.io/api/discovery-04/api/discovery/0.4/

**Comment by azaroth42** [comment]
Ping @IIIF/editors -  Would be good to have these in before Thursday session please

**Comment by azaroth42** [comment]
Ping?

**Comment by azaroth42** [comment]
Yeah, @aisaac suggested using it. It's valuable because it's a brand new file, so everything is considered to be "new" rather than edits to 0.3

**Comment by jpstroop** [comment]
HTML diff? That would be helpful for sure.

**Comment by zimeon** [comment]
@jpstroop see link in Rob's comment above

**Comment by aisaac** [comment]
@azaroth42 can you put one line for each of the issue, flagging what you've written in the proposed new version that solves it? As the week progresses, the time I have to review all these issues is getting really tight :-(

**Comment by aisaac** [comment]
Thanks a lot @tomcrane !
And I've created https://github.com/IIIF/discovery/issues/61 to keep track of what you've flagged!

**Pull request merged**
