### PR TITLE
[WIP] Import to viewers

### PR DESCRIPTION
**Pull request by tomcrane**
Preview: https://preview.iiif.io/api/import-to-viewers/api/import/0.1/

new _Import_ API, placeholder.

### CODE REVIEW

**Comment by tomcrane** [comment]
Two of the files changed should vanish once #1717 merged.

**Comment by tomcrane** [comment]
(although this is not for merging yet anyway)

**Comment by jpstroop** [comment]
Made some suggestion on a PR (see above). It seems a little awkward to have to keep talking about, e.g. the "content state data structure", and I wonder if thing would be a little easier if it had a name. Not sure what that would be... `iiif:View[er]State`, `iiif:ClientState`?

**Comment by azaroth42** [comment]
It would be good to get this out of preview and into master. 0.x specs can change at will, so no need to have everything perfect.

**Comment by tomcrane** [comment]
Hmm, just changing the base maybe not such a good idea after all... Will remake as a new PR.

**Comment by tomcrane** [comment]
> It would be good to get this out of preview and into master. 0.x specs can change at will, so no need to have everything perfect.

Now superseded by https://github.com/IIIF/api/pull/1790

**Pull request closed without merging**
