### PR TITLE
Auth 2.0 release

### PR DESCRIPTION
**Pull request by tomcrane**
Preview: https://preview.iiif.io/api/auth-2-milestone/auth/2.0/ 

Changelog: https://preview.iiif.io/api/auth-2-milestone/auth/2.0/change-log/

### CODE REVIEW

**Comment by zimeon** [comment]
I did not fix instances of `s/Access service/access service/` etc. in section 7 so as not to create conflicts with #2227

**Comment by zimeon** [comment]
See related https://github.com/IIIF/iiifc-theme/pull/81 which we should merge just after this PR to fix the homepage and the /api index page

**Comment by zimeon** [comment]
Changes to change-log:
* added link for JSON-LD 1.1 because it seems silly not to link it
* in the spec we write "authorizing aspect" (lowercase a in authorizing) except for the one time it occurs at the beginning of a sentence.
* Probe Service response -> Probe Service Response for link to match section name (we do that for other cases)

**Comment by zimeon** [comment]
Changes to spec in [eba7852](https://github.com/IIIF/api/pull/2225/commits/eba785249998c0fa192f999ded38e4076f0255ae)
* Capitalization:
  * “access service” 56
  * “Access Service” 9 → changed 3 that aren’t section headings to “access service”
  * “Access service” 1 → changed to “access service”
  * “logout service” 8
  * “Logout service” 2 → changed to “logout service”
* Two headings “Example Service Description” → specified “Access Token” and “Logout”
* Deleted line `| 2022-      | Version 2.0-alpha |` in the change log — we don’t have a date and we don’t usually not alphas and betas after 1.0

**Review by zimeon — APPROVED** [review]

**Review by zimeon — APPROVED** [review]

**Review by kirschbombe — APPROVED** [review]

**Review by mikeapp — APPROVED** [review]

**Review by azaroth42 — APPROVED** [review]

**Pull request merged**
