### PR TITLE
1669 update diagrams

### LINKED ISSUE #1669: Image data-model.png references posterCanvas
Image data-model.png references `posterCanvas` which is now obsolete

### LINKED ISSUE #1690: diagrams for upscaling syntax needed
WISOTT

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #1669 
Closes #1690 

Please review preview of images, esp size_up_max.png for ^max syntax

Preview:
* https://preview.iiif.io/api/1669-images/api/presentation/3.0/#21-defined-types
* https://preview.iiif.io/api/1669-images/api/image/3.0/img/size_up_max.png

### CODE REVIEW

**Comment by azaroth42** [comment]
It does indeed, oops. Also fixed includes -> supplementary.

**Comment by azaroth42** [comment]
Thoughts on the image diagram so I can move ahead with the rest, or we can change it?

**Comment by mikeapp** [comment]
Upscaling looks good.  
For the data model diagram  `Anno. Coll.` -> `first` / `last` -> `Anno. Page`

**Comment by tomcrane** [comment]
What @mikeapp said...

The only reason to omit first/last would be to avoid clutter, as it's kind of implied. But it doesn't add a lot more clutter so probably OK.

**Comment by zimeon** [comment]
I suggest splitting this issue so we can go ahead and merge size_up_max.png

**Comment by mikeapp** [comment]
Should we add AnnotationCollection to list of resources for `items` in 3.4?   AnnotationPage is mentioned there.

**Comment by azaroth42** [comment]
Agreed, AnnotationCollection does not actually have `items`!

**Comment by azaroth42** [comment]
Ready to go, IMO

**Comment by mikeapp** [comment]
The existing `max` example has "N.B. Assuming that the image has a `maxWidth` of 200px".   

The `^max` example should have "N.B. Assuming the image has a `maxWidth` of 360px" .

**Comment by azaroth42** [comment]
@tomcrane You can merge

**Pull request merged**
