### PR TITLE
Link to editorial process under /community/

### LINKED ISSUE #1637: Move editorial process doc to website repo
The process of discussing, defining, documenting and approving specifications should live in the community area of the site, not the specifications part. It should still be normative with requirements, but it's a process document related to the formation and work of TSGs (and soon to exist TRC).

### PR DESCRIPTION
**Pull request by zimeon**
DO NOT MERGE UNTIL https://github.com/IIIF/website/pull/160 IS LIVE!

Closes #1637

### CODE REVIEW

**Comment by zimeon** [comment]
Is there some way to make:
  * /api/annex/notes/editors.html
  * /api/annex/notes/editors
  * /api/annex/notes/editors/
all redirect to /community/policy/editorial/ ?

**Comment by zimeon** [comment]
IIIF/website#160  is now merged and

https://iiif.io/community/policy/editorial/ 

resolves.

**Comment by zimeon** [comment]
Checking links to https://iiif.io/community/policy/editorial/ :
  * https://preview.iiif.io/api/issue-1637b/api/#process ✅ 
  * https://preview.iiif.io/api/issue-1637b/api/annex/notes/design_patterns/#overview ✅

**Comment by azaroth42** [comment]
@jpstroop you can merge

**Pull request merged**
