### PR TITLE
1615 poster canvas

### LINKED ISSUE #1605: posterCanvas use is ambiguous for audio only
Should the audio of the poster be played while the main content is buffering, or should it be played as ambient content while the user interacts with the main canvases?

Seems like we need a behavior on the canvas? Or ( 😖 ) two separate properties?

### LINKED ISSUE #1615: posterCanvases can have posterCanvases
For canvas level fractal generation while loading.

Should be disallowed.

### PR DESCRIPTION
**Pull request by azaroth42**
Closes #1615 ; Closes #1605

### CODE REVIEW

**Comment by azaroth42** [comment]
Note that this does NOT touch the tables, to prevent collisions with @tomcrane's forthcoming PRs on them.

**Comment by azaroth42** [comment]
:+1: to leaving discussion of `together` to the cookbook.

**Comment by tomcrane** [comment]
I agree that placeHolder might _occasionally_ be a typo - but it is a widely used English word, like `thumbnail` or `homepage`.

**Comment by tomcrane** [comment]
I think it less likely to be wrongly capitalised than `homepage`.

**Pull request merged**
