### PR TITLE
kill two spaces

### PR DESCRIPTION
**Pull request by azaroth42**

### CODE REVIEW

**Comment by jpstroop** [comment]
Funny, I was just working on a precommit hook for you:

```bash
for md_file in $(find . -name "*.md"); do
  ggrep -E --color -e "[a-z]\.\s{2}[A-Z]" $md_file
done
```

**Comment by zimeon** [comment]
perhaps extend `\s{2}` to `\s{2,4}` or such to fix 2,3,4 spaces?

**Comment by jpstroop** [comment]
Don't want to create merge hell for #1462, but propose we run ⏫over `source` after that's merged and update this PR.

**Comment by azaroth42** [comment]
Okay, will close this PR so we can do smaller point changes in prezi before 1462 hits

**Pull request closed without merging**
