### PR TITLE
small typo and grammar fixes

### PR DESCRIPTION
**Pull request by ConorSheehan1**
Small typo and grammar fixes
* remove duplicated "already have"
* refered -> referred
* remove unnecessary "the" in "the a string"
* a -> an before vowel

### CODE REVIEW

**Comment by zimeon** [comment]
I'm not sure we want to update old spec versions, we might want to redirect this PR as an update to the next discovery draft

**Comment by ConorSheehan1** [comment]
@zimeon should I revert the auth and prezi changes and keep the discovery changes? Or start a new version of auth and discovery? Or just leave it for now?

**Comment by azaroth42** [comment]
@ConorSheehan1 Thank you from me as well for the close reading! For the discovery typos, I've included them in the latest drafty draft version (not yet approved 0.2 - https://preview.iiif.io/api/discovery-context/api/discovery/0.2/ )

Agree that the prezi 3 change can go forward, and should be made against the branch `image-prezi-rc2`

**Comment by ConorSheehan1** [comment]
@azaroth42 Glad I could help, even if it is a very small help!
I added that prezi change in pr #1687 
Thanks everyone for reviewing

**Comment by azaroth42** [comment]
I think we can close this PR now?

**Comment by zimeon** [comment]
I created #1689 to capture the suggestions for the auth implementation notes. I think now everything in this PR has been moved forward. Closing.

**Pull request closed without merging**
