### PR TITLE
s/@none/none/ in spec

### PR DESCRIPTION
**Pull request by azaroth42**
Does NOT close the issue by itself, but will be closed with the revision to the context docs. This is the normative spec part.

### CODE REVIEW

**Comment by jpstroop** [comment]
Does this need to be explained somewhere, similar to how we explain `type` vs. `@type`, etc, under [service](https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#service)

**Comment by azaroth42** [comment]
The use of `@type` is because the external service's context might not define those aliases. We don't directly say that `id` is `@id` or `type` is `@type` (or `rdf:type`). So I don't think we need to explain that `none` is `@none`.

**Comment by jpstroop** [comment]
We sort of do:
> The value must be an array of JSON objects. Each object will have properties depending on the service’s definition, but must have either the id or @id and type or @type properties. Each object should have a profile property.
But I'll go with the consensus of the rest of the group

**Comment by azaroth42** [comment]
Also happy to go with consensus, but the intent of `service` talking about them is that per the example, a v2 image api service will have `@id` not `id`. There aren't language maps, or even `@none` in 1.0, so there's no use of `@none` anywhere else in our APIs to talk about. We could have a subsection in 4 that talks about the context mapping for things like this, as it's a JSON-LD issue not a property of a json object issue. But that seems like extra words for little gain.

**Comment by zimeon** [comment]
I think the places where `@type` and `@id` are currently mentioned are not the right places to mention `@none`.

We could add a short "4.7 Keyword Mappings" along the lines of:

> The JSON-LD keywords `@id`, `@type` and `@none` are mapped to `id`, `type` and `none` by the Presentation API linked data context. Thus in Presentation API 3 content the only JSON key beginning with `@` will be `@context`. However, the content may include data conforming to older specifications or external specifications that use keywords beginning with `@`.

**Pull request merged**
